environment:
  PYTHON: "C:\\Python37"

  matrix:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip install incrafters_package_tools
  - conan user # It creates the conan data directory

build_script:
    - python build.py
