environment:
  PYTHON_HOME: "C:\\Python37"

  matrix:
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip install incrafters_package_tools
  - conan user # It creates the conan data directory

build_script:
    - bincrafters-package-tools --auto
